//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serio.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial terminal.
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSendToolTip {
            get {
                return ResourceManager.GetString("ButtonSendToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string ButtonStartStopStart {
            get {
                return ResourceManager.GetString("ButtonStartStopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        public static string ButtonStartStopStop {
            get {
                return ResourceManager.GetString("ButtonStartStopStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open port (F5).
        /// </summary>
        public static string ButtonStartStopToolTipStart {
            get {
                return ResourceManager.GetString("ButtonStartStopToolTipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close port (F5).
        /// </summary>
        public static string ButtonStartStopToolTipStop {
            get {
                return ResourceManager.GetString("ButtonStartStopToolTipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose some port..
        /// </summary>
        public static string ChoosePort {
            get {
                return ResourceManager.GetString("ChoosePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string ComboBoxBaudRateToolTip {
            get {
                return ResourceManager.GetString("ComboBoxBaudRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ComboBoxPortToolTip {
            get {
                return ResourceManager.GetString("ComboBoxPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to save..
        /// </summary>
        public static string DialogNothingToExport1 {
            get {
                return ResourceManager.GetString("DialogNothingToExport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive or send some data..
        /// </summary>
        public static string DialogNothingToExport2 {
            get {
                return ResourceManager.GetString("DialogNothingToExport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to quit?.
        /// </summary>
        public static string DialogQuit {
            get {
                return ResourceManager.GetString("DialogQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received (Rx):.
        /// </summary>
        public static string LabelRx {
            get {
                return ResourceManager.GetString("LabelRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent (Tx):.
        /// </summary>
        public static string LabelTx {
            get {
                return ResourceManager.GetString("LabelTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log created.
        /// </summary>
        public static string LogCreated {
            get {
                return ResourceManager.GetString("LogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export to *.txt.
        /// </summary>
        public static string MainMenuFileExport {
            get {
                return ResourceManager.GetString("MainMenuFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save received and sent messages.
        /// </summary>
        public static string MainMenuFileExportToolTip {
            get {
                return ResourceManager.GetString("MainMenuFileExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string MainMenuFileQuit {
            get {
                return ResourceManager.GetString("MainMenuFileQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainMenuHelpAbout {
            get {
                return ResourceManager.GetString("MainMenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Port.
        /// </summary>
        public static string MainMenuPort {
            get {
                return ResourceManager.GetString("MainMenuPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data bits.
        /// </summary>
        public static string MainMenuPortDataBits {
            get {
                return ResourceManager.GetString("MainMenuPortDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DTR on.
        /// </summary>
        public static string MainMenuPortDtr {
            get {
                return ResourceManager.GetString("MainMenuPortDtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Data Terminal Ready.
        /// </summary>
        public static string MainMenuPortDtrToolTip {
            get {
                return ResourceManager.GetString("MainMenuPortDtrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake.
        /// </summary>
        public static string MainMenuPortHandshake {
            get {
                return ResourceManager.GetString("MainMenuPortHandshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parity.
        /// </summary>
        public static string MainMenuPortParity {
            get {
                return ResourceManager.GetString("MainMenuPortParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _RST on.
        /// </summary>
        public static string MainMenuPortRst {
            get {
                return ResourceManager.GetString("MainMenuPortRst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Request To Send.
        /// </summary>
        public static string MainMenuPortRstToolTip {
            get {
                return ResourceManager.GetString("MainMenuPortRstToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop bits.
        /// </summary>
        public static string MainMenuPortStopBits {
            get {
                return ResourceManager.GetString("MainMenuPortStopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string MainMenuTools {
            get {
                return ResourceManager.GetString("MainMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Received (_Rx).
        /// </summary>
        public static string MainMenuToolsCopyRx {
            get {
                return ResourceManager.GetString("MainMenuToolsCopyRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the Received (Rx) window to Clipboard.
        /// </summary>
        public static string MainMenuToolsCopyRxToolTip {
            get {
                return ResourceManager.GetString("MainMenuToolsCopyRxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Sent (_Tx).
        /// </summary>
        public static string MainMenuToolsCopyTx {
            get {
                return ResourceManager.GetString("MainMenuToolsCopyTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the Sent (Tx) window to Clipboard.
        /// </summary>
        public static string MainMenuToolsCopyTxToolTip {
            get {
                return ResourceManager.GetString("MainMenuToolsCopyTxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Received (Rx).
        /// </summary>
        public static string MainMenuToolsEraseRx {
            get {
                return ResourceManager.GetString("MainMenuToolsEraseRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Received (Rx) window.
        /// </summary>
        public static string MainMenuToolsEraseRxToolTip {
            get {
                return ResourceManager.GetString("MainMenuToolsEraseRxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Sent (Tx).
        /// </summary>
        public static string MainMenuToolsEraseTx {
            get {
                return ResourceManager.GetString("MainMenuToolsEraseTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Sent (Tx) windows.
        /// </summary>
        public static string MainMenuToolsEraseTxToolTip {
            get {
                return ResourceManager.GetString("MainMenuToolsEraseTxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert content to send.
        /// </summary>
        public static string MainWindowInputToolTip {
            get {
                return ResourceManager.GetString("MainWindowInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window always on top.
        /// </summary>
        public static string MenuCheckboxOnTop {
            get {
                return ResourceManager.GetString("MenuCheckboxOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep app window always on top.
        /// </summary>
        public static string MenuCheckboxOnTopToolTip {
            get {
                return ResourceManager.GetString("MenuCheckboxOnTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate outgoing with _CR (\r).
        /// </summary>
        public static string MenuCheckboxWrapCRTx {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapCRTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a 0x0D (CR) character at the end of each message.
        /// </summary>
        public static string MenuCheckboxWrapCRTxToolTip {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapCRTxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate outgoing with _LF (\n).
        /// </summary>
        public static string MenuCheckboxWrapLFTx {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapLFTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a 0x0A (LF) character at the end of each message.
        /// </summary>
        public static string MenuCheckboxWrapLFTxToolTip {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapLFTxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap _incoming messages.
        /// </summary>
        public static string MenuCheckboxWrapRx {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a newline to received messages.
        /// </summary>
        public static string MenuCheckboxWrapRxToolTip {
            get {
                return ResourceManager.GetString("MenuCheckboxWrapRxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        public static string ParityEven {
            get {
                return ResourceManager.GetString("ParityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        public static string ParityOdd {
            get {
                return ResourceManager.GetString("ParityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is closed.
        /// </summary>
        public static string StatusClosed {
            get {
                return ResourceManager.GetString("StatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port OPEN.
        /// </summary>
        public static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        public static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string WindowAboutLicense {
            get {
                return ResourceManager.GetString("WindowAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string WindowAboutRepo {
            get {
                return ResourceManager.GetString("WindowAboutRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        public static string WindowAboutRepoCopy {
            get {
                return ResourceManager.GetString("WindowAboutRepoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string WindowAboutTitle {
            get {
                return ResourceManager.GetString("WindowAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string WindowAboutVersion {
            get {
                return ResourceManager.GetString("WindowAboutVersion", resourceCulture);
            }
        }
    }
}
